name: CI
on: [push]
jobs:
        build:
                strategy:
                        matrix:
                                os: ['3.9', '3.10']
                
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v1
                        - name: setup python ${{matrix.os}}
                          uses: actions/setup-python@v2
                          with:
                                  python-version: ${{matrix.os}}
                        - name: Install dependeices
                          run: |
                                  python -m pip install --upgrade pip
                                  pip install tox tox-gh-actions
                        - name: Test with tox
                          run: tox
                        - name: run the python
                          run: python test.py
